version: '3.9'

services:
  tiffinmate.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__PostgreSQL=Host=tiffinmate.db;Database=tiffinmate_db;Username=postgres_user;Password=postgres_password
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      # Mount local directories for live code reloading during development
      - ./TiffinMate.API:/app
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - tiffinmate.db

  tiffinmate.db:
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: tiffinmate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
    driver: local
