name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build --build-arg JWT_KEY="${{ secrets.JWT_KEY }}" --build-arg JWT_REFRESH_KEY="${{ secrets.JWT_REFRESH_KEY }}" --build-arg DEFAULT_CONNECTION="${{ secrets.DEFAULT_CONNECTION }}" --build-arg HOST_URL="${{ secrets.HOST_URL }}" --build-arg HOST_API="${{ secrets.HOST_API }}" --build-arg TWILIO_SID="${{ secrets.TWILIO_SID }}" --build-arg TWILIO_TOKEN="${{ secrets.TWILIO_TOKEN }}" --build-arg TWILIO_VERIFY_SID="${{ secrets.TWILIO_VERIFY_SID }}" --build-arg BREVO_API_KEY="${{ secrets.BREVO_API_KEY }}" --build-arg BREVO_API_URL="${{ secrets.BREVO_API_URL }}" --build-arg BREVO_FROM_EMAIL="${{ secrets.BREVO_FROM_EMAIL }}" --build-arg CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}" --build-arg CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}" --build-arg CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}" -t sabithmk7/tiffinmate-api-prod:latest .

      - name: Publish Image to Docker Hub
        run: docker push sabithmk7/tiffinmate-api-prod:latest   

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull sabithmk7/tiffinmate-api-prod:latest
      - name: Delete Old Container
        run: docker rm -f tiffinmate-api
      - name: Run New Docker Container
        run: docker run -d -p 8080:8080 -e JWT_KEY="${{ secrets.JWT_KEY }}" -e JWT_REFRESH_KEY="${{ secrets.JWT_REFRESH_KEY }}" -e DEFAULT_CONNECTION="${{ secrets.DEFAULT_CONNECTION }}" -e HOST_URL="${{ secrets.HOST_URL }}" -e HOST_API="${{ secrets.HOST_API }}" -e TWILIO_SID="${{ secrets.TWILIO_SID }}" -e TWILIO_TOKEN="${{ secrets.TWILIO_TOKEN }}" -e TWILIO_VERIFY_SID="${{ secrets.TWILIO_VERIFY_SID }}" -e BREVO_API_KEY="${{ secrets.BREVO_API_KEY }}" -e BREVO_API_URL="${{ secrets.BREVO_API_URL }}" -e BREVO_FROM_EMAIL="${{ secrets.BREVO_FROM_EMAIL }}" -e CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}" -e CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}" -e CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}" --name tiffinmate-api sabithmk7/tiffinmate-api-prod:latest
