name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t sabithmk7/tiffinmate-api-prod:latest .

      - name: Publish Image to Docker Hub
        run: docker push sabithmk7/tiffinmate-api-prod:latest   

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH Access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull sabithmk7/tiffinmate-api-prod:latest
            docker rm -f tiffinmate-api || true
            docker run -d -p 8080:80 --name tiffinmate-api sabithmk7/tiffinmate-api-prod:latest
          EOF
